package src;

interface IFormulasDanio{
    double FACTOR_NIVEL_AGUA = 0.7,
    FACTOR_PRESION_AGUA = 0.3,
    FACTOR_NIVEL_FUEGO = 0.8,
    FACTOR_TEMPERATURA_LLAMA = 0.2,
    FACTOR_NIVEL_PLANTA = 0.6,
    FACTOR_DENSIDAD_ESPORAS = 0.4,
    MULTIPLICADOR_VENTAJA = 2.0,
    MULTIPLICADOR_DESVENTAJA = 0.5;
}